version: "3.4"

services:
  postgresql:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=wordling_dev
